### ISSUE TITLE
Update OpenShift blog links

### ISSUE THREAD

**Issue by magick93** [CrunchyData/crunchy-containers#109]
Hi

I'm wanting to get started using Crunchy on OpenShift, and was reading the excellent article on https://blog.openshift.com/openshift-ecosystem-crunchy-postgresql-integration/ however all the links to the Crunchy repo are broken, so its not possible to follow along.

Is it possible for the links to be corrected, and the files references in the article to be made public again?

**Comment by jmccormick2001** [comment]
it appears I can't update that page unfortunately...way back when, I renamed that project to the new crunchy-containers repo name, things have changed greatly since that blog was written, I encourage you to take a look at the docs folder within this repo, particularly the files ending ".asciidoc", they contain a lot of materials to get you started and updated.  regards.
