### ISSUE TITLE
Why were the postgres-ha directories removed in v5.0.3?

### ISSUE THREAD

**Issue by mayankn** [CrunchyData/crunchy-containers#1464]
Can someone please tell me why the build/postgres-ha, conf/postgres-ha and bin/postgres-ha directories were removed in v5.0.3 onwards? They are present in v4.7.6. I was hoping to use the latest v5.1.2 tag to build the postgres-ha container but cannot do so, so just looking for some explanation

**Comment by mayankn** [comment]
@jkatz or @andrewlecuyer would either of you know?

**Comment by andrewlecuyer** [comment]
@mayankn the specific directories you referenced - along with the files within them - are applicable to PGO v4 only.  Therefore, with the `master` branch in this repository now supporting [PGO v5](https://access.crunchydata.com/documentation/postgres-operator/v5/), the files and directories you referenced have been removed (since they are no longer needed).
