### ISSUE TITLE
Is there any rpm packages difference?

### ISSUE THREAD

**Issue by Eric-zch** [CrunchyData/crunchy-containers#1531]
By reading container image Dockerfiles, it seems Crunchy use a private repository to get Postgres related rpm packages like: 
postgresql, pgaudit, pg_partman, pg_cron, pgbackrest, timescaledb, wal2json,etc. 
```
bash-4.4$ rpm -qa | grep -i crunchy
crunchy-backrest-2.41-0Crunchy.el8.x86_64
pgaudit_analyze-1.0.8-1Crunchy.el8.x86_64
python3-psycopg2-2.9.3-0Crunchy.el8.x86_64
passwordpolicy-1.0.0-0Crunchy.el8.x86_64
pgaudit14_set_user-3.0.0-0Crunchy.el8.x86_64
pg_partman_14-4.7.1-0Crunchy.el8.x86_64
pgnodemx14-1.4-1Crunchy.el8.x86_64
pgaudit14-1.6.2-0Crunchy.el8.x86_64
wal2json_14-2.5-0Crunchy.el8.x86_64
orafce_14-3.25.1-0Crunchy.el8.x86_64
timescaledb_14-2.8.1-0Crunchy.el8.x86_64
...
```
My question is:
(1) Is there any difference between the packages in the private repository and corresponding packages in Postgres community repository (https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-8-x86_64/)? especially for pgbackrest.

(2) If the packages are the same, why do not use the packages in Postgres community repository?

Thank you.

**Comment by andrewlecuyer** [comment]
That is correct.

The Dockerfiles associated with this repository make use of the RPMs associated with Crunchy Postgres, our Postgres distribution, in order to build Crunchy Postgres for Kubernetes.

We don't track the differences between the Crunchy Postgres RPMs and PGDG RPMs, but the Crunchy Postgres RPMs go through our own build / testing / certification process.

**Comment by Eric-zch** [comment]
Hi @andrewlecuyer 
Thanks for the explanation.
