### ISSUE TITLE
Postgres Data will be lost

### ISSUE THREAD

**Issue by mehdy** [CrunchyData/crunchy-containers#17]
There's a problem with postgres data that are stored in a volume. if by any reason I terminate the pod, Kubernetes will recreate it, maybe on the same node(everything's ok) or maybe on another node(all data will be lost).

what's your solution for this?

**Comment by rimusz** [comment]
@mehdy use persistent disk to store the database state

**Comment by jmccormick2001** [comment]
correct, you will want to use NFS, gluster, Ceph, or one of the supported persistent volume types supported within Kube/OSE.  I typically use NFS for my testing just because it can be shared
between multiple pods, and also because its easy to setup...but I've got it to also work with Ceph and Gluster as well.  Take a look at one of the NFS examples within the Openshift examples directory.  Also, within the docs/install.asciidoc I describe how to install NFS and set it up for this purpose.  cheers.
