### ISSUE TITLE
Data Persistence

### ISSUE THREAD

**Issue by orondon** [CrunchyData/crunchy-containers#376]
Hi CrunchyData team
I'm trying with Docker swarm to map /pgdata to a local data volume.
It worked out by setting up the local folder permissions with owner user postgres UID 26.
When the DB master starts, I do a restore from a dump
cat dumpfile | psql -d myDB
This works by creating /pgdata/container_id/....
My problem is how can this data persist so that I don't need a restore after every service restart?
When I restart the service, a new folder is created /pgdata/new_container_id/...
So I need to restore every time from backup.

Is there anyway to maybe change /pgdata/... without the subfolder for the container_id ?

Thanks a lot!
Ornella

**Comment by jmccormick2001** [comment]
you might try out setting this environment variable in the postgres container, it will let you override the path that is created or looked for...
* PGDATA_PATH_OVERRIDE - if set, will cause the container to use a /pgdata path
   name of your choosing rather than the hostname of the container which
   is the default. This is useful for a primary in a deployment.

**Comment by jasonodonnell** [comment]
@orondon Two ways to fix this:

* `PGDATA_PATH_OVERRIDE` environment variable as @jmccormick2001 mentioned
* Specify a hostname (`docker run --hostname=primary`)

**Comment by jasonodonnell** [comment]
@orondon Let us know if this helped.  Will close due to inactivity soon.  Thanks!

**Comment by orondon** [comment]
This worked. You may close. Thanks.
