### ISSUE TITLE
Examples.adoc empty section and non-compliant double quotes

### ISSUE THREAD

**Issue by cmwshang** [CrunchyData/crunchy-containers#487]
Both these issues are in the file examples.adoc:

1.  There is an empty section ===== Kubernetes Secrets. It is followed immediately by another section ===== Secrets. Maybe ===== Secrets should be removed as redundant since there is no subsection under that?

2.  Double quoted text is not asciidoc compliant. According to  http://asciidoc.org/userguide.html#X51, they should be enclosed with ``two grave accents to the left and two acute accents to the right''. So this statement:
it will use the Kubernetes API to discover pods with the label *"crunchy-collect": "true"*.
should be
it will use the Kubernetes API to discover pods with the label *``crunchy-collect'': ``true''*.

And just as an FYI, an admonition paragraph in asciidoc is expected to begin as the first word of the paragraph, capitalized with a colon following. For example: 
NOTE: This is my note.
WARNING: This is my warning.
See http://asciidoc.org/userguide.html#X28.

**Comment by cmwshang** [comment]
containers.adoc has the same statement as 2. above with the non-compliant double quotes.

**Comment by xenophenes** [comment]
I'm happy to fix the other things you mentioned, however the double-quotes standard you mentioned is not rendered correctly in GitHub which is currently our primary means of displaying documentation.

For example, if you look at examples.adoc at the sections you fixed:

> CRUNCHY DATA SOLUTIONS, INC. PROVIDES THIS GUIDE ``AS IS'' WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.

You can see the quotes are displayed literally rather than being translated. Likewise, replacing the quotes in these code blocks makes them render *really oddly* and I would not recommend doing this as long as our primary form of documentation viewing is through GitHub.

@jmccormick2001 , I leave that decision up to you, however.

**Comment by cmwshang** [comment]
GitHub repository has it's own "flavor" of asciidoc and if there is a problem with how the GitHub renderer displays the asciidoc markup, then we need to submit a bug report, which I will do.  If we are to use adoc files as the source for building our documentation in HTML, PDF and markdown, then we cannot deviate from the standards just to overcome an issue with the Github display.

Cynthia Shang
www.crunchydata.com

**Comment by xenophenes** [comment]
This issue will have to be placed on hold until GitHub fixes this bug. Please let me know when you receive an update from their team.

**Comment by cmwshang** [comment]
I disagree but we will take this offline with the parties involved.

**Comment by jmccormick2001** [comment]
thanks to all for chasing this down...for now since we use github for our docs site, we need the quoting to look correct to users...if github fixes this rendering we will come back and update to get our docs to the standard format, but for now I think we have done as much as we can.  contact me if you feel we need to resolve differently and thank you for reporting this and making the docs better and more compliant.
