### ISSUE TITLE
pgbouncer - failover

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#489]
either fix failover logic in pgbouncer or remove it entirely from the docs and code base.

**Comment by sfrost** [comment]
Is there a description of what the issue is with the failover logic?  I've not seen issues *in* pgbouncer regarding this, but if there's a problem there then we should be able to get it addressed upstream.  I'm guessing that there's an issue in how we're using it though, and I'd be happy to try and help address that.  I'd certainly rather not see pgbouncer removed from the docs or codebase as we routinely recommend it to clients as an excellent connection pooler which can be used for failover.

**Comment by jmccormick2001** [comment]
its totally in my code on this one and how I wrote it 3 yrs ago, pgbouncer is working I think as expected.  we'll keep pgbouncer container for sure however, its just the failover part of that integration that I need to re-do and make right again.

**Comment by sfrost** [comment]
Ok, if there's anything I can do to help, please let me know.  I can certainly answer questions regarding pgbouncer in the near-term, in the slightly longer-term (post-March), I could take a look at diving in myself to try and see what's going on and see if I can debug it.  I'd really like to make sure we get pgbouncer solid as I see a lot of upcoming deployments where it would be a great fit.
