### ISSUE TITLE
Refactor pgdump and pgrestore containers

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#551]
**I'm submitting a ...**

 
 - [ ] bug report
 - [X] feature request
 - [ ] support request

**What is the current behavior?**

The `pgdump` and `pgrestore` containers are very complicated. 

**What is the motivation or use case for changing the behavior?**

These containers need to be reduced down to basic automated functionality but allow a single environment override if users have advanced use cases.

**Comment by the1forte** [comment]
The default pgdump could be a plain format SQL dump using pg_dumpall as the postgres user. I think that's a good basic default. The different format choices could be exposed somewhere in the examples docs. I prefer a directory format as my advanced use case, for example.

The pgrestore example really just needs access to the dump location. I feel like this should mount the same pgdump-pvc. Making a new pvc for the restore example is misleading, and only works because it points to the same working example directory. The PGRESTORE_VOLUMEPATH could default to most recent dump directory if none is specified.
