### ISSUE TITLE
pre and post hooks for postgres container

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#627]
allow for pre-init and post-start bash script execution in the postgres container start script.

 
 - [ ] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by flamingdumpster** [comment]
How flexible do we want this to be?

 **Flexible:** pre-init / post-start script names defined by user in an environment variable

**Less flexible:** user has to create specifically named scripts, as defined in the start.sh or common_lib.sh (defined in common_lib.sh if script names are relevant beyond start.sh)

In either case, if they are defined, exist and are executable, they run, otherwise ignored without error.

**Comment by jmccormick2001** [comment]
for 2.0, we can just use predefined script names, 'pre-hook.sh' or 'post-hook.sh' or similar.

**Comment by flamingdumpster** [comment]
The description specifies only the postgres container. Are there any other containers we want to do this for?
