### ISSUE TITLE
create or convert backrest examples to use env vars

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#786]
the most recent version of backrest supports environment variables as a means to configure backrest, our current examples use config files, this Issue is to replace or add examples of specifying the configuration using env vars.

 
 - [ ] bug report
 - [x ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by jmccormick2001** [comment]
the backrest script under bin/postgres would need to change with this, instead of looking for a config file under /pgconf/pgbackrest.conf to trigger its actions, it would instead need to look for an 
environment variable like PGBACKREST_STANZA.

**Comment by jmccormick2001** [comment]
also includes converting backrest_restore container which as it also runs backrest commands would also be a candidate for using env vars instead of config files.

**Comment by andrewlecuyer** [comment]
Since @jasonodonnell implemented pgbackrest env support for the **crunchy-postgres** container in Containers v2.2.0 (including a backup example for Docker & Kube), I will be focusing on the following:

- Adding pgbackrest env var support to the **crunchy-backrest-restore** container
- Adding Docker and Kube examples for using **crunchy-backrest-restore** with env vars
- Adding the pgbackrest backup and restore examples to the Containers documentation

**Comment by andrewlecuyer** [comment]
I will be removing use of the **pgbackrest.conf** configuration file from all containers, examples, etc.  Environment variables with therefore now be the officially supported method for configuring pgbackreset.
